### ISSUE TITLE
Audio is still crackling on 6p on prolonged use

### ISSUE THREAD

**Issue by ryburke** [FunktronicLabs/zenvr#3]

**Comment by eddietree** [comment]
i think i fixed it? maybe?

do u have an extra iphone 6p for me to test?

**Comment by jonathanschaefferhookqa** [comment]
I haven't tested this on a Nexus 6P however I've seen this happen on the Pixel Devices, occurs after only a few minutes of use.

**Comment by eddietree** [comment]
Thanks @jonathanschaefferhookqa! would u mind letting me know which build (commit number is fine) you've tested on? I don't have a pixel to use currently

**Comment by jonathanschaefferhookqa** [comment]
@eddietree I used the URL found here http://zenvr.funktroniclabs.com/29/ for testing.

**Comment by eddietree** [comment]
Thanks @jonathanschaefferhookqa ! I've updated the version since then, can you please QA on this version?

http://zenvr.funktroniclabs.com/30/

moving forward, will you be testing directly from pulling from github, or did u want me to make builds for you to test?

**Comment by jonathanschaefferhookqa** [comment]
@eddietree 

If you can make us builds that would be great, if its not too much trouble. I also logged a few additional issues today, I'll go through them tomorrow and confirm they are still an issue on the latest build.

**Comment by ryburke** [comment]
@jonathanschaefferhookqa To your last comment, can you confirm that the issues you observed with v29 persisted with v30?

**Comment by lucasmarianohookqa** [comment]
Audio sounds good on /30 using Pixel.
