### ISSUE TITLE
Site is not formatted to the portrait orientation 

### ISSUE THREAD

**Issue by jonathanschaefferhookqa** [FunktronicLabs/zenvr#4]
Description:
If the user views the site on a Pixel device in the portrait orientation then its not formatted correctly. I didn't have any issues when I viewed the site in Landscape orientation.

Browser Platform:
Pixel Android 7.1.1 Chrome Beta 56
Pixel XL Android 7.1.1 Chrome Beta 56

URL:
http://zenvr.funktroniclabs.com/29/

Steps:
Navigate to the Site's URL on a Pixel Device
Notice that the Site does not display properly on the device

![screenshot_20161219-142625](https://cloud.githubusercontent.com/assets/14283709/21333889/055f9112-c608-11e6-9b81-9c3136550929.png)

**Comment by eddietree** [comment]
@jonathanschaefferhookqa fixed in upcoming version, will be 31. will update soon

![2017-01-09 14_47_26-chromatic vr](https://cloud.githubusercontent.com/assets/71531/21786791/a34de1d0-d67a-11e6-9ddd-0a05889a2037.png)
