### ISSUE TITLE
Sound from the app can be heard even if the Browser is suspended

### ISSUE THREAD

**Issue by jonathanschaefferhookqa** [FunktronicLabs/zenvr#6]
Description:
If the user views the site while the sound is playing then puts the browser in a suspended state the sound of the app can still be heard.

Browser Platform:
Pixel Android 7.1.1 Chrome Beta 56
Pixel XL Android 7.1.1 Chrome Beta 56

URL:
http://zenvr.funktroniclabs.com/29/

Steps:
Navigate to the Site's URL on a Pixel Device
Either start the experience or leave it on the Home Screen
Note the sound playing
Put the Browser in the background
Notice that the sound is still audible

**Comment by eddietree** [comment]
fixed in new version

http://zenvr.funktroniclabs.com/30
