### ISSUE TITLE
The Framerate can be a bit low during certain sections of the experience

### ISSUE THREAD

**Issue by jonathanschaefferhookqa** [FunktronicLabs/zenvr#7]
Description:
Overall the Performance / Framerate of the experience is pretty good when used on a Pixel device, however occasionally it appears that the Framerate dips or stutters.

Note: This might be resolved when the newest versions of Chrome are released that support WebVR, currently I'm using the Chrome Beta 56 with the WebVR flags enabled.

Browser Platform:
Pixel Android 7.1.1 Chrome Beta 56
Pixel XL Android 7.1.1 Chrome Beta 56

URL:
http://zenvr.funktroniclabs.com/29/

Steps:
Navigate to the Site's URL on a Pixel Device
Start the experience by selecting "Enter VR" and putting the device in the Headset
View the experience
Notice that certain sections of the experience have a low framerate.

**Comment by eddietree** [comment]
can you test further ones on this one?

http://zenvr.funktroniclabs.com/30

**Comment by eddietree** [comment]
@jonathanschaefferhookqa i did a complete optimization pass on the graphics (should be 2x faster) and audio for build 30, let me know if you are still having that issue

**Comment by lucasmarianohookqa** [comment]
frame rate was noticeably better on /30
