### ISSUE TITLE
255 word app description

### ISSUE THREAD

**Issue by ryburke** [FunktronicLabs/zenvr#9]
Eddie - take a crack at a 255 word description for Chromatic and we'll help polish up.

**Comment by ryburke** [comment]
Reference: https://www.chromeexperiments.com/experiment/land-lines

**Comment by eddietree** [comment]
@ryburke 

added here: https://docs.google.com/document/d/1oAHPea9WUGHRdMaJpPoj7EOmGFn0OvbKQfFKr0R8mqw/edit?usp=sharing
